# Generated by Django 3.2.5 on 2021-07-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passkey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passkey',
            name='username',
            field=models.CharField(default='AmodhShenoy', max_length=30),
        ),
    ]
